/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PokemonGuesserRouteImport } from './routes/pokemon-guesser'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DamageCalculatorRouteImport } from './routes/damage-calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumSlugRouteImport } from './routes/forum/$slug'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as ForumSlugIndexRouteImport } from './routes/forum/$slug/index'
import { Route as AuthGoogleIndexRouteImport } from './routes/auth/google/index'
import { Route as ForumSlugNewRouteImport } from './routes/forum/$slug/new'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as ForumSlugThreadThreadIdRouteImport } from './routes/forum/$slug/thread/$threadId'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonGuesserRoute = PokemonGuesserRouteImport.update({
  id: '/pokemon-guesser',
  path: '/pokemon-guesser',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageCalculatorRoute = DamageCalculatorRouteImport.update({
  id: '/damage-calculator',
  path: '/damage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugRoute = ForumSlugRouteImport.update({
  id: '/forum/$slug',
  path: '/forum/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugIndexRoute = ForumSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumSlugRoute,
} as any)
const AuthGoogleIndexRoute = AuthGoogleIndexRouteImport.update({
  id: '/auth/google/',
  path: '/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugNewRoute = ForumSlugNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ForumSlugRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugThreadThreadIdRoute = ForumSlugThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => ForumSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/games': typeof GamesRoute
  '/pokemon-guesser': typeof PokemonGuesserRoute
  '/showcase': typeof ShowcaseRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/forum/$slug/new': typeof ForumSlugNewRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/forum/$slug/': typeof ForumSlugIndexRoute
  '/forum/$slug/thread/$threadId': typeof ForumSlugThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/games': typeof GamesRoute
  '/pokemon-guesser': typeof PokemonGuesserRoute
  '/showcase': typeof ShowcaseRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/forum/$slug/new': typeof ForumSlugNewRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/forum/$slug': typeof ForumSlugIndexRoute
  '/forum/$slug/thread/$threadId': typeof ForumSlugThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/games': typeof GamesRoute
  '/pokemon-guesser': typeof PokemonGuesserRoute
  '/showcase': typeof ShowcaseRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/forum/$slug/new': typeof ForumSlugNewRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/forum/$slug/': typeof ForumSlugIndexRoute
  '/forum/$slug/thread/$threadId': typeof ForumSlugThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/damage-calculator'
    | '/games'
    | '/pokemon-guesser'
    | '/showcase'
    | '/auth/logout'
    | '/forum/$slug'
    | '/auth/google/callback'
    | '/forum/$slug/new'
    | '/auth/google'
    | '/forum/$slug/'
    | '/forum/$slug/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/damage-calculator'
    | '/games'
    | '/pokemon-guesser'
    | '/showcase'
    | '/auth/logout'
    | '/auth/google/callback'
    | '/forum/$slug/new'
    | '/auth/google'
    | '/forum/$slug'
    | '/forum/$slug/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/damage-calculator'
    | '/games'
    | '/pokemon-guesser'
    | '/showcase'
    | '/auth/logout'
    | '/forum/$slug'
    | '/auth/google/callback'
    | '/forum/$slug/new'
    | '/auth/google/'
    | '/forum/$slug/'
    | '/forum/$slug/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DamageCalculatorRoute: typeof DamageCalculatorRoute
  GamesRoute: typeof GamesRoute
  PokemonGuesserRoute: typeof PokemonGuesserRoute
  ShowcaseRoute: typeof ShowcaseRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ForumSlugRoute: typeof ForumSlugRouteWithChildren
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleIndexRoute: typeof AuthGoogleIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon-guesser': {
      id: '/pokemon-guesser'
      path: '/pokemon-guesser'
      fullPath: '/pokemon-guesser'
      preLoaderRoute: typeof PokemonGuesserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-calculator': {
      id: '/damage-calculator'
      path: '/damage-calculator'
      fullPath: '/damage-calculator'
      preLoaderRoute: typeof DamageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug': {
      id: '/forum/$slug'
      path: '/forum/$slug'
      fullPath: '/forum/$slug'
      preLoaderRoute: typeof ForumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug/': {
      id: '/forum/$slug/'
      path: '/'
      fullPath: '/forum/$slug/'
      preLoaderRoute: typeof ForumSlugIndexRouteImport
      parentRoute: typeof ForumSlugRoute
    }
    '/auth/google/': {
      id: '/auth/google/'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug/new': {
      id: '/forum/$slug/new'
      path: '/new'
      fullPath: '/forum/$slug/new'
      preLoaderRoute: typeof ForumSlugNewRouteImport
      parentRoute: typeof ForumSlugRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug/thread/$threadId': {
      id: '/forum/$slug/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/forum/$slug/thread/$threadId'
      preLoaderRoute: typeof ForumSlugThreadThreadIdRouteImport
      parentRoute: typeof ForumSlugRoute
    }
  }
}

interface ForumSlugRouteChildren {
  ForumSlugNewRoute: typeof ForumSlugNewRoute
  ForumSlugIndexRoute: typeof ForumSlugIndexRoute
  ForumSlugThreadThreadIdRoute: typeof ForumSlugThreadThreadIdRoute
}

const ForumSlugRouteChildren: ForumSlugRouteChildren = {
  ForumSlugNewRoute: ForumSlugNewRoute,
  ForumSlugIndexRoute: ForumSlugIndexRoute,
  ForumSlugThreadThreadIdRoute: ForumSlugThreadThreadIdRoute,
}

const ForumSlugRouteWithChildren = ForumSlugRoute._addFileChildren(
  ForumSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DamageCalculatorRoute: DamageCalculatorRoute,
  GamesRoute: GamesRoute,
  PokemonGuesserRoute: PokemonGuesserRoute,
  ShowcaseRoute: ShowcaseRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ForumSlugRoute: ForumSlugRouteWithChildren,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleIndexRoute: AuthGoogleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
