/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokemonGuesserRouteImport } from './routes/pokemon-guesser'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DamageCalculatorRouteImport } from './routes/damage-calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'

const PokemonGuesserRoute = PokemonGuesserRouteImport.update({
  id: '/pokemon-guesser',
  path: '/pokemon-guesser',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageCalculatorRoute = DamageCalculatorRouteImport.update({
  id: '/damage-calculator',
  path: '/damage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/games': typeof GamesRoute
  '/pokemon-guesser': typeof PokemonGuesserRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/games': typeof GamesRoute
  '/pokemon-guesser': typeof PokemonGuesserRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/games': typeof GamesRoute
  '/pokemon-guesser': typeof PokemonGuesserRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/damage-calculator'
    | '/games'
    | '/pokemon-guesser'
    | '/auth/google'
    | '/auth/logout'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/damage-calculator'
    | '/games'
    | '/pokemon-guesser'
    | '/auth/google'
    | '/auth/logout'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/damage-calculator'
    | '/games'
    | '/pokemon-guesser'
    | '/auth/google'
    | '/auth/logout'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DamageCalculatorRoute: typeof DamageCalculatorRoute
  GamesRoute: typeof GamesRoute
  PokemonGuesserRoute: typeof PokemonGuesserRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/pokemon-guesser': {
      id: '/pokemon-guesser'
      path: '/pokemon-guesser'
      fullPath: '/pokemon-guesser'
      preLoaderRoute: typeof PokemonGuesserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-calculator': {
      id: '/damage-calculator'
      path: '/damage-calculator'
      fullPath: '/damage-calculator'
      preLoaderRoute: typeof DamageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
  }
}

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DamageCalculatorRoute: DamageCalculatorRoute,
  GamesRoute: GamesRoute,
  PokemonGuesserRoute: PokemonGuesserRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
